<?php
$labels = array();
$labels['aliases'] = 'Alias';
$labels['autoreply'] = "Activer";
$labels['autoreplybutton'] = 'Sauvegarder';
$labels['autoreplymessage'] = 'Message';
$labels['autoreplysubject'] = 'Sujet';
$labels['failed'] = 'Echec !';
$labels['forward'] = 'Paramètres de transferts';
$labels['forwardingaddresses'] = 'Transférer à';
$labels['keepcopy'] = 'Conserver une copie de l\'email';
$labels['mailforward'] = 'Transfert de messages';
$labels['outofoffice'] = 'Message d\'absence';
$labels['separate_alias'] = 'Séparer chaque alias par une virgule';
$labels['separate_forward'] = 'Séparer chaque adresse de transfert par une virgule';
$labels['success_changed'] = 'Paramètres de message d\'absence enregistrés avec succès';
$labels['vacation'] = 'Répondeur';
$labels['autoreplyactivefrom'] = 'Date de début';
$labels['autoreplyactiveuntil'] = 'Date de fin';
// Button text
$labels['aliasesbutton'] = 'Récupérer les alias';
?>
